#!/bin/sh
#
# 20-banner - MOTD ascii art banner

cat << 'EOF'

          _,met$$$$$gg.
       ,g$$$$$$$$$$$$$$$P.
     ,g$$P""       """Y$$.".
    ,$$P'              `$$$. 
  ',$$P       ,ggs.     `$$b:
  `d$$'     ,$P"'   .    $$$
   $$P      d$'     ,    $$P
   $$:      $$.   -    ,d$$'
   $$;      Y$b._   _,d$P'
   Y$$.    `.`"Y$$$$P"' 
   `$$b      "-.__     
    `Y$$b              
     `Y$$.             
       `$$b.           
         `Y$$b.        
           `"Y$b._     
               `""""
EOF
